### ISSUE TITLE
Error with api

### ISSUE THREAD

**Issue by SergioPolanco** [rapidpro/rapidpro-python#48]
Hi everyone, I need your help

I'm getting this error with I try add a contact

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/media/sergio/Respaldo/UNICEF/app_web/unicef_app/administrador/views.py", line 54, in post
    client.create_contact(name=data["name"], language=None, urns=None, fields=data["fields"], groups=data["groups"])
  File "/usr/local/lib/python2.7/dist-packages/temba_client/v2/__init__.py", line 297, in create_contact
    return Contact.deserialize(self._post('contacts', None, payload))
  File "/usr/local/lib/python2.7/dist-packages/temba_client/clients.py", line 63, in _post
    return self._request('post', url, params=params, body=payload)
  File "/usr/local/lib/python2.7/dist-packages/temba_client/clients.py", line 352, in _request
    return super(BaseCursorClient, self)._request(method, url, params=params, body=body)
  File "/usr/local/lib/python2.7/dist-packages/temba_client/clients.py", line 101, in _request
    raise TembaNoSuchObjectError()
TembaNoSuchObjectError: No such object exists

Thanks

**Comment by rowanseymour** [comment]
Hi Sergio. Can you make other API calls like fetching contacts?

**Comment by SergioPolanco** [comment]
I haven't been able to replicate the error, and everything seems to be working fine now.It was probably an issue on my end. Thanks
